name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: python -m pip install --upgrade pip
      - run: pip install mkdocs-material==9.1.4
      - run: pip install pillow cairosvg
      - run: mkdocs gh-deploy --force
